# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_joiner', models.ManyToManyField(related_name='joingame', to='loginreg.User')),
                ('game_starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersstarts', to='loginreg.User')),
            ],
            managers=[
                ('gameManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('players', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gametype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gametypesgame', to='gameapp.GameType')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gametype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamestype', to='gameapp.GameType'),
        ),
    ]
